name = "authelia"
type = "cli"

[platform.linux]
download-file = "authelia-v{version}-linux-{arch}.tar.gz"

[install]
download-url = "https://github.com/authelia/authelia/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/authelia/authelia/releases/download/v{version}/checksums.sha256"
unpack = true

[install.arch]
x86_64 = "amd64"
aarch64 = "arm64"

[resolve]
git-url = "https://github.com/authelia/authelia"
git-tag-pattern = "^v(.*)$"
