# https://github.com/PlakarKorp/plakar
name = "plakar"
type = "cli"

[resolve]
git-url = "https://github.com/PlakarKorp/plakar"

[platform.linux]
download-file = "plakar_{version}_linux_{arch}.tar.gz"
checksum-file = "plakar_{version}_checksums.txt"

[platform.macos]
download-file = "plakar_{version}_darwin_{arch}.tar.gz"
checksum-file = "plakar_{version}_checksums.txt"

[platform.windows]
download-file = "plakar_{version}_windows_{arch}.tar.gz"
exe-path = "plakar.exe"
checksum-file = "plakar_{version}_checksums.txt"

[install]
download-url = "https://github.com/PlakarKorp/plakar/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/PlakarKorp/plakar/releases/download/v{version}/{checksum_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
