# https://github.com/BurntSushi/ripgrep
name = "ripgrep"
type = "cli"

[resolve]
git-url = "https://github.com/BurntSushi/ripgrep"

[platform.linux]
download-file = "ripgrep-{version}-{arch}-unknown-linux-musl.tar.gz"
checksum-file = "ripgrep-{version}-{arch}-unknown-linux-musl.tar.gz.sha256"
archive-prefix = "ripgrep-{version}-{arch}-unknown-linux-musl"
bin-path = "rg"

[install]
download-url = "https://github.com/BurntSushi/ripgrep/releases/download/{version}/{download_file}"
checksum-url = "https://github.com/BurntSushi/ripgrep/releases/download/{version}/{checksum_file}"
unpack = true

[install.arch]
x86_64 = "x86_64"
